# Generated by Django 5.2.17 on 2026-09-09 12:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('legal_name', models.CharField(blank=True, max_length=200)),
                ('tax_id', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('OWNER', 'Proprietário'), ('ADMIN', 'Administrador'), ('TEACHER', 'Professor'), ('STUDENT', 'Aluno')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('INVITED', 'Convidado'), ('ACTIVE', 'Ativo'), ('SUSPENDED', 'Suspenso'), ('INACTIVE', 'Inativo')], db_index=True, default='ACTIVE', max_length=20)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='institutions.institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('institution__name', 'role'),
                'indexes': [models.Index(fields=['institution', 'role'], name='membership_inst_role_idx'), models.Index(fields=['user', 'status'], name='membership_user_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'institution'), name='unique_user_institution_membership')],
            },
        ),
    ]
