# Generated by Django 5.2.17 on 2026-09-11 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_migrate_existing_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Proprietário'), ('ADMIN', 'Administrador'), ('COORDINATOR', 'Coordenador'), ('TEACHER', 'Professor'), ('STUDENT', 'Aluno')], db_index=True, max_length=20),
        ),
    ]
