# Generated by Django 5.2.17 on 2026-09-01 02:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('assessment_type', models.CharField(choices=[('EXAM', 'Prova'), ('ASSIGNMENT', 'Trabalho'), ('PROJECT', 'Projeto'), ('ACTIVITY', 'Atividade')], db_index=True, default='EXAM', max_length=20)),
                ('max_score', models.DecimalField(decimal_places=2, default=10, max_digits=6)),
                ('weight', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('assessment_date', models.DateField()),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='academics.classgroup')),
            ],
            options={
                'ordering': ('assessment_date', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='grading.assessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='academics.studentprofile')),
            ],
            options={
                'ordering': ('assessment', 'student'),
            },
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.CheckConstraint(condition=models.Q(('max_score__gt', 0)), name='assessment_max_score_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gt', 0)), name='assessment_weight_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.UniqueConstraint(fields=('class_group', 'title', 'assessment_date'), name='unique_assessment_class_title_date'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0)), name='grade_score_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('assessment', 'student'), name='unique_grade_per_assessment_student'),
        ),
    ]
